### ISSUE TITLE
Please change "WIP - iSCToolbox" for "iSCT (Work in Progress)"

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox_web#42]
some people might not know what WIP means.

**Comment by wpinaud** [comment]
![capture d ecran 2015-10-14 a 14 19 04](https://cloud.githubusercontent.com/assets/11258860/10483240/8de8607e-727e-11e5-86b1-e0cf4f232bc1.png)

Will be updated asap on the server.
