### ISSUE TITLE
not possible to create new user

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox_web#44]
![screen shot 2015-10-14 at 10 39 31](https://cloud.githubusercontent.com/assets/2482071/10486999/e6557e6e-725f-11e5-9481-a4d34d4400d6.png)

**Comment by wpinaud** [comment]
Yes, you already have an account (created last time, when we have tested the website for the first time)

Also the version on the server is really old, I haven't updated since the end of my internship.
I wanted to wait until the next release, but I can do it this weekend if you want.

**Comment by jcohenadad** [comment]
yes please, could you update the version on the server-- i'd like to have a beta version that works for our grant proposal

also, could you delete my account (i don't remember which passwd i used, so i will re-create one)
thanks!

**Comment by wpinaud** [comment]
Yes, in the new version you have an administration page where you can easily
delete users.
I will add an option to send a mail to update the password, that will be
useful in this case.
