### ISSUE TITLE
create an iSCT version that works with minimal functionalities 

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox_web#45]
Current problems are:
- old version on the server-- need to update
- not possible to upload data
- create youtube video for "how to" demonstration

**Comment by poquirion** [comment]
We can now log properly and load data.

Visu is still down...

**Comment by wpinaud** [comment]
Visu is OK now

**Comment by wpinaud** [comment]
and section handling is working

**Comment by poquirion** [comment]
Up and running! 

I will upload the video on the wiki. And add a link in the page header.
