### ISSUE TITLE
option for toolbox

### ISSUE THREAD

**Issue by poquirion** [neuropoly/spinalcordtoolbox_web#46]
All options are not always showing, especially -i and -o

**Comment by poquirion** [comment]
I am aving a look at the `PluginUpdater` class

**Comment by poquirion** [comment]
seems to be on the view side

**Comment by wpinaud** [comment]
I'm working on that

**Comment by wpinaud** [comment]
That was on my side  :+1: 
I improved the way to handle section, now it's working for every case.

Now we have a beautiful form, automatically generated
![capture d ecran 2015-10-30 a 15 46 51](https://cloud.githubusercontent.com/assets/11258860/10848884/75f256bc-7f1e-11e5-8fa9-da6fefe58e49.png)
