### ISSUE TITLE
toolbox not loading

### ISSUE THREAD

**Issue by poquirion** [neuropoly/spinalcordtoolbox_web#48]
Damn it. It only seems to be a reload problem, but can't track it.

**Comment by wpinaud** [comment]
fixed : I have commented the `@access_info` decorator.
It forces decorated route to return 'None'

Now we have a beautiful :
![capture d ecran 2015-10-30 a 15 36 22](https://cloud.githubusercontent.com/assets/11258860/10848826/16645b1e-7f1e-11e5-8d72-369ba4616872.png)
